cc_library(
    name = "base",
    visibility = ["//src/engine:__subpackages__"],
    hdrs = [
        "bus.h",
        "constants.h",
        "log.h",
        "registers.h",
    ],
    srcs = [
        "log.cc",
    ],
)
