cc_library(
    name = "public",
    visibility = ["//visibility:public"],
    hdrs = [
        "bus.h",
        "constants.h",
        "event_logger.h",
        "instruction.h",
        "registers.h",
    ]
)
