cc_library(
    name = "public",
    visibility = ["//src/engine:__subpackages__"],
    hdrs = [
        "bus.h",
        "constants.h",
        "event_logger.h",
        "instruction.h",
        "registers.h",
    ]
)
