package(default_visibility = ["//visibility:public"],)

load(":rom.bzl", "rom")

rom(name = "100_nops", asms = ["100_nops.s"])
rom(name = "branch_test", asms = ["branch_test.s"])
rom(name = "ppu_test", asms = ["ppu_test.s"])
