package(default_visibility = ["//visibility:public"],)

load(":rom.bzl", "rom")

rom(name = "nop_test", asms = ["nop_test.s"])
rom(name = "pretty_log_test", asms = ["pretty_log_test.s"])
rom(name = "branch_test", asms = ["branch_test.s"])
